![display](https://miro.medium.com/v2/resize:fit:1400/1*2EHWC8rFLkeuY9V-ydKUZg.gif)

![display](https://miro.medium.com/v2/resize:fit:960/1*TqcA9EIUF-DGGTBhIx_qbQ.gif)

![display](https://easyai.tech/wp-content/uploads/2022/08/3877f-2019-07-02-output.gif)

![display](https://easyai.tech/wp-content/uploads/2022/08/f0116-2019-07-02-rnn-1.gif)

In [ ]:
# LSTM(long short term memory)

![display](https://miro.medium.com/v2/resize:fit:640/format:webp/0*NIFLmgpE4TDRBwh4.gif)

# Tokenization

In [ ]:
s='this is work tokenization.'
t=list(s)
t

['t',
 'h',
 'i',
 's',
 ' ',
 'i',
 's',
 ' ',
 'w',
 'o',
 'r',
 'k',
 ' ',
 't',
 'o',
 'k',
 'e',
 'n',
 'i',
 'z',
 'a',
 't',
 'i',
 'o',
 'n',
 '.']

In [ ]:
s='this is word tokenization.'
t=s.split()
t

['this', 'is', 'word', 'tokenization.']

In [ ]:
s='this is para.It has multiple sentences,so we can use it for splitting  the,. This is call as sentence tokenization.'
t=s.split('.')
t

['this is para',
 'It has multiple sentences,so we can use it for splitting  the,',
 ' This is call as sentence tokenization',
 '']

# Embeding:

Terms:


*   corpus- all words
*   vocabulory-unique words


*   document- each observation/record





In [ ]:
d={'good teaching':1,
   'bad teaching':0,
   'amazing teacher':1,
   'wrost teacher':0,
   'excellent teacher':1}

w=[]
for i in d:
  w +=(i.split())
print('corpus:',len(w))
print('vocabulory:',len(set(w)))
print('document:',len(d))

corpus: 10
vocabulory: 7
document: 5


In [ ]:
print(w)
v={}
print(set(w))
for i in set(w):
  v[i]=w.count(i)
print(v)

['good', 'teaching', 'bad', 'teaching', 'amazing', 'teacher', 'wrost', 'teacher', 'excellent', 'teacher']
{'teacher', 'wrost', 'excellent', 'amazing', 'good', 'teaching', 'bad'}
{'teacher': 3, 'wrost': 1, 'excellent': 1, 'amazing': 1, 'good': 1, 'teaching': 2, 'bad': 1}


In [ ]:
l=[]
for i in d:
  l1=[]
  for j in v.keys():
    if j in i:
      l1.append(v[j])
    else:l1.append(0)
  l.append(l1)
print(l)

[[0, 0, 0, 0, 1, 2, 0], [0, 0, 0, 0, 0, 2, 1], [3, 0, 0, 1, 0, 0, 0], [3, 1, 0, 0, 0, 0, 0], [3, 0, 1, 0, 0, 0, 0]]


In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [ ]:
df=pd.DataFrame(l,columns=v.keys())
df

NameError: name 'l' is not defined

In [ ]:
dt=np.array(l)
dt

array([[0, 0, 0, 0, 1, 2, 0],
       [0, 0, 0, 0, 0, 2, 1],
       [3, 0, 0, 1, 0, 0, 0],
       [3, 1, 0, 0, 0, 0, 0],
       [3, 0, 1, 0, 0, 0, 0]])

In [ ]:
dt.shape

(5, 7)

In [ ]:
dt=np.reshape(dt,(dt.shape[0],dt.shape[1],1))
dt

array([[[0],
        [0],
        [0],
        [0],
        [1],
        [2],
        [0]],

       [[0],
        [0],
        [0],
        [0],
        [0],
        [2],
        [1]],

       [[3],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0]],

       [[3],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0]],

       [[3],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0]]])

In [ ]:
dt.shape

(5, 7, 1)

In [ ]:
x=tf.convert_to_tensor(dt,dtype=tf.float32)
x

<tf.Tensor: shape=(5, 7, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [2.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [2.],
        [1.]],

       [[3.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.]],

       [[3.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[3.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.]]], dtype=float32)>

In [ ]:
x.shape

TensorShape([5, 7, 1])

In [ ]:
y=np.array(list(d.values()))
y

array([1, 0, 1, 0, 1])

In [ ]:
m = keras.Sequential()
m.add(keras.layers.SimpleRNN(1,activation='sigmoid',input_shape=(7,1)))
m.add(keras.layers.Dense(12,activation='sigmoid'))
m.add(keras.layers.Dense(1,activation='sigmoid'))
m.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
m.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)             │ (None, 1)                   │               3 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 12)                  │              24 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              13 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
m.fit(x,y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.6000 - loss: 0.6831


In [ ]:
p=m.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step


In [ ]:
p

array([[0.5337752 ],
       [0.5357928 ],
       [0.53445005],
       [0.5344762 ],
       [0.5344843 ]], dtype=float32)

# **Applying RNN on dataset**

In [ ]:
! pip install -q kaggle
from google.colab import files
files.upload()
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

Saving kaggle.json to kaggle.json


In [ ]:
!kaggle competitions download -c fake-news

 88% 41.0M/46.5M [00:00<00:00, 46.4MB/s]
100% 46.5M/46.5M [00:01<00:00, 48.6MB/s]


In [ ]:
! pip install patool

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 9.6 MB/s eta 0:00:00


In [ ]:
import patoolib

In [ ]:
patoolib.extract_archive("/content/fake-news.zip")

INFO patool: Extracting /content/fake-news.zip ...
INFO:patool:Extracting /content/fake-news.zip ...
INFO patool: running /usr/bin/7z x -o./Unpack_zge4dd2d -- /content/fake-news.zip
INFO:patool:running /usr/bin/7z x -o./Unpack_zge4dd2d -- /content/fake-news.zip
INFO patool:     with input=''
INFO:patool:    with input=''
INFO patool: ... /content/fake-news.zip extracted to `fake-news' (multiple files in root).
INFO:patool:... /content/fake-news.zip extracted to `fake-news' (multiple files in root).


'fake-news'

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [ ]:
df=pd.read_csv('/content/fake-news/train.csv',index_col='id')
df

title  \
id                                                         
0      House Dem Aide: We Didn’t Even See Comey’s Let...   
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2                      Why the Truth Might Get You Fired   
3      15 Civilians Killed In Single US Airstrike Hav...   
4      Iranian woman jailed for fictional unpublished...   
...                                                  ...   
20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799                          What Keeps the F-35 Alive   

                                          author  \
id                                                 
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
id                                                               
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 4 columns]

In [ ]:
df.shape

(20800, 4)

In [ ]:
x=df.drop('label',axis=1)
x.head(10)

title  \
id                                                      
0   House Dem Aide: We Didn’t Even See Comey’s Let...   
1   FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2                   Why the Truth Might Get You Fired   
3   15 Civilians Killed In Single US Airstrike Hav...   
4   Iranian woman jailed for fictional unpublished...   
5   Jackie Mason: Hollywood Would Love Trump if He...   
6   Life: Life Of Luxury: Elton John’s 6 Favorite ...   
7   Benoît Hamon Wins French Socialist Party’s Pre...   
8   Excerpts From a Draft Script for Donald Trump’...   
9   A Back-Channel Plan for Ukraine and Russia, Co...   

                          author  \
id                                 
0                  Darrell Lucus   
1                Daniel J. Flynn   
2             Consortiumnews.com   
3                Jessica Purkiss   
4                 Howard Portnoy   
5                Daniel Nussbaum   
6                            NaN   
7                Alissa J. Rubin   
8                            NaN   
9   Megan Twohey and Scott Shane   

                                                 text  
id                                                     
0   House Dem Aide: We Didn’t Even See Comey’s Let...  
1   Ever get the feeling your life circles the rou...  
2   Why the Truth Might Get You Fired October 29, ...  
3   Videos 15 Civilians Killed In Single US Airstr...  
4   Print \nAn Iranian woman has been sentenced to...  
5   In these trying times, Jackie Mason is the Voi...  
6   Ever wonder how Britain’s most iconic pop pian...  
7   PARIS  —   France chose an idealistic, traditi...  
8   Donald J. Trump is scheduled to make a highly ...  
9   A week before Michael T. Flynn resigned as nat...

In [ ]:
y=df['label']

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences   # used for sequence padding is necesary when dealing  with sequences of variable of lengths, as neural networks typically required fixed size input.
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras.layers import Dense

In [ ]:
# Note :
# An embedding layers is often sued to convert discreate tokens (like words) into continuous vector representations.
# This vector representations caprire semantic relationship between words.
# allowing the neural network to better unserstand the meaning of the words in the input data

In [ ]:
# ! pip install nltk              Natural language Toolkit (NLTK) Libarary in python.

In [ ]:
import nltk
import re
from nltk.corpus import stopwords                      # NLTK's stopwords corpus provides a collection of stopwords in various lanaguages.

In [ ]:
voc=5000

In [ ]:
n=x['title'].copy()
n.head(10)

id
0    House Dem Aide: We Didn’t Even See Comey’s Let...
1    FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                    Why the Truth Might Get You Fired
3    15 Civilians Killed In Single US Airstrike Hav...
4    Iranian woman jailed for fictional unpublished...
5    Jackie Mason: Hollywood Would Love Trump if He...
6    Life: Life Of Luxury: Elton John’s 6 Favorite ...
7    Benoît Hamon Wins French Socialist Party’s Pre...
8    Excerpts From a Draft Script for Donald Trump’...
9    A Back-Channel Plan for Ukraine and Russia, Co...
Name: title, dtype: object

# **Stremmer:**

In [ ]:
# stopwatch = unimportant words
nltk.download('stopwords',download_dir=r'C:\Users\Admin\Desktop\Stopwords')
nltk.data.path.append(r'C:\Users\Admin\Desktop\Stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\Desktop\Stopwords...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
df.shape

(20800, 4)

In [ ]:
from nltk.stem.porter import PorterStemmer  # porter stremming algorithm is used ti reduce words to thier base or root from , which helps in capturing the essence of words
ps= PorterStemmer()
cp=[]
for i in n:
  print(i)
  review=re.sub('[^a-zA-Z]',' ',str(i))
  #print(review)
  review=review.lower().split()
  #print(review)

  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  #print(review)
  review=' '.join(review)
  #print(review)
  cp.append(review)

Streaming output truncated to the last 5000 lines.
At Least 18 Die as Tornadoes Sweep Southeast U.S. - The New York Times
Armed Citizen Who Threw Wallet to Distracted Suspect: ’That’s When I Lit Him Up’ - Breitbart
The End of the Anglo-American Order - The New York Times
O’Keefe: Dems, Left, and Media Should Be Asked If They Disavow Violent Inauguration Protesters
Watch as Russia launches its latest super-stealth submarine
China repeatedly hacked US, stole data on nukes, FBI & war plans
Merkel: Worried about Islamisation? Just Sing Christmas Carols
BREAKING : Hillary Clinton Had her MAID Print CLASSIFIED INFORMATION – TruthFeed
California’s Big Sur, Highway 1 Closed By Massive Landslide - Breitbart
C.I.A. Developed Tools to Spy on Mac Computers, WikiLeaks Disclosure Shows - The New York Times
Robert Osborne, Turner Classic Movies Host, Dies at 84 - The New York Times
Liberal Democrat Leader Branded ’Bigot’ for Refusing to Endorse Gay Sex
nan
ATF Permanently Relocating More Agents to Vi

In [ ]:
cp

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'life life luxuri elton john favorit shark pictur stare long transcontinent flight',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'excerpt draft script donald trump q ampa black church pastor new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find hom

## **One Hot**

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
oh = [one_hot(w,voc)for w in cp]
oh

[[2020, 3397, 4699, 849, 3490, 3946, 2053, 3411, 4694, 1836],
 [3702, 1155, 4487, 3807, 4528, 158, 3751],
 [3114, 1736, 4347, 695],
 [959, 862, 2354, 2879, 36, 2075],
 [343, 4528, 2296, 4737, 2356, 703, 4528, 821, 4342, 195],
 [4302,
  4306,
  1987,
  1304,
  785,
  4748,
  1557,
  3387,
  2290,
  3658,
  2305,
  4525,
  3861,
  3686,
  3751],
 [602, 602, 4165, 1068, 2232, 13, 2204, 1964, 4483, 3241, 3120, 3141],
 [427, 672, 4759, 3932, 1761, 3464, 1572, 420, 845, 2354, 3410],
 [355, 3889, 4485, 2419, 4748, 4767, 3913, 1892, 3996, 1194, 845, 2354, 3410],
 [4221, 1916, 1902, 3203, 4302, 4347, 4748, 724, 845, 2354, 3410],
 [1632, 3702, 188, 3450, 583, 1400, 752, 66, 4748, 4928],
 [2137, 4426, 4536, 4159, 2859, 4973, 3661, 3696],
 [1280, 254, 2618, 342, 1053, 4010, 2867, 1703, 2509, 2868, 3199],
 [2879, 3416, 3490, 1400, 4748, 4302],
 [4588, 1969, 4144, 1761, 3635, 4431, 3862, 156, 3476],
 [692, 2366, 4106, 4269, 105, 4191, 4183, 845, 2354, 3410],
 [4551, 361, 141, 1276, 4156, 845, 2354, 

# **Embedding**

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
sen=20
em=pad_sequences(oh ,padding='pre',maxlen=20)
print(em)

[[   0    0    0 ... 3411 4694 1836]
 [   0    0    0 ... 4528  158 3751]
 [   0    0    0 ... 1736 4347  695]
 ...
 [   0    0    0 ...  845 2354 3410]
 [   0    0    0 ... 2454 3320 2774]
 [   0    0    0 ...  137 3053 1886]]


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras.layers import Dense

# **Building RNN**

In [ ]:
emb_features=20
n=Sequential()
n.add(Embedding(voc,emb_features,input_length=sen))
n.add(SimpleRNN(10800))
n.add(Dense(1,activation='sigmoid'))
n.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
n.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# sen = np.array(oh).shape[1]

# Redefine the model with the correct input length
n = Sequential()
n.add(Embedding(voc, emb_features, input_length=sen))
n.add(SimpleRNN(100))
n.add(Dense(1, activation='sigmoid'))
n.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

n.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_1 (SimpleRNN)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
len(em),y.shape

(20800, (20800,))

In [ ]:
x=np.array(em)
y=np.array(y)

In [ ]:
x.shape, y.shape

((20800, 20), (20800,))

In [ ]:
from sklearn.model_selection import train_test_split
xtn,xts,ytn,yts=train_test_split(x,y,test_size=0.2,random_state=8)

In [ ]:
n.fit(xtn,ytn,epochs=20)

Epoch 1/20
520/520 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.8613 - loss: 0.3272
Epoch 2/20
520/520 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9595 - loss: 0.1086
Epoch 3/20
520/520 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.9885 - loss: 0.0373
Epoch 4/20
520/520 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.9967 - loss: 0.0111
Epoch 5/20
520/520 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9990 - loss: 0.0038
Epoch 6/20
520/520 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9993 - loss: 0.0036
Epoch 7/20
520/520 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 1.0000 - loss: 0.0021
Epoch 8/20
520/520 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 1.0000 - loss: 2.8787e-04
Epoch 9/20
520/520 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 1.0000 - loss: 6.7864e-05
Epoch 10/20
520/520 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 1.0000 - loss: 3.6362e-05
Epoch 11/20
520/520 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 1.0000 - loss: 2.5156e-05
Epoch 12/20
520/520 ━━━━━━━━━━━━━━━━

In [ ]:
pred=n.predict(xts)
print(len(pred))
pred

130/130 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
4160


array([[1.2218940e-10],
       [1.2683829e-13],
       [9.9999678e-01],
       ...,
       [3.3308998e-09],
       [6.4959496e-02],
       [1.0000000e+00]], dtype=float32)

In [ ]:
print(len(yts))

4160


In [ ]:
np.argmax(pred[0])

0

In [ ]:
y_pred=pred.argmax(axis=1)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(yts,y_pred)

0.5028846153846154